development:
  adapter: postgresql
  database: taco_manager
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: taco_manager_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: taco_manager_prod
  pool: 5
  timeout: 5000
  host: localhost
